-- JobRunr MCP hub: accounts, tokens and connected instances. Portable between H2 and PostgreSQL.
-- The hub never stores tool arguments, tool results or job data.

CREATE TABLE IF NOT EXISTS hub_accounts (
    id          VARCHAR(36)   PRIMARY KEY,
    email       VARCHAR(320)  NOT NULL UNIQUE,
    name        VARCHAR(200)  NOT NULL,
    company     VARCHAR(200)  NOT NULL,
    job_role    VARCHAR(200),
    use_case    VARCHAR(1000),
    cluster_id  VARCHAR(64),
    created_at  TIMESTAMP     NOT NULL,
    verified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hub_tokens (
    id           VARCHAR(36)  PRIMARY KEY,
    account_id   VARCHAR(36)  NOT NULL,
    kind         VARCHAR(16)  NOT NULL,
    scope        VARCHAR(16),
    token_hash   VARCHAR(64)  NOT NULL UNIQUE,
    hint         VARCHAR(8)   NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    revoked_at   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hub_magic_links (
    token_hash VARCHAR(64) PRIMARY KEY,
    account_id VARCHAR(36) NOT NULL,
    expires_at TIMESTAMP   NOT NULL,
    used_at    TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hub_sessions (
    token_hash VARCHAR(64) PRIMARY KEY,
    account_id VARCHAR(36) NOT NULL,
    expires_at TIMESTAMP   NOT NULL
);

CREATE TABLE IF NOT EXISTS hub_instances (
    account_id         VARCHAR(36)  PRIMARY KEY,
    cluster_id         VARCHAR(64),
    jobrunr_version    VARCHAR(40),
    java_version       VARCHAR(40),
    framework          VARCHAR(40),
    storage_provider   VARCHAR(100),
    redaction          BOOLEAN,
    servers            INT,
    recurring_jobs     BIGINT,
    jobs_scheduled     BIGINT,
    jobs_enqueued      BIGINT,
    jobs_processing    BIGINT,
    jobs_failed        BIGINT,
    jobs_succeeded     BIGINT,
    first_connected_at TIMESTAMP,
    snapshot_at        TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hub_tool_calls (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  VARCHAR(36)  NOT NULL,
    tool_name   VARCHAR(64)  NOT NULL,
    success     BOOLEAN      NOT NULL,
    latency_ms  BIGINT       NOT NULL,
    user_agent  VARCHAR(300),
    occurred_at TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS hub_lead_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  VARCHAR(36)  NOT NULL,
    event       VARCHAR(64)  NOT NULL,
    detail      VARCHAR(500),
    occurred_at TIMESTAMP    NOT NULL
);
